name: Setup NoMount
description: Clone and Integrate NoMount in kernel
inputs:
  version:
    description: 'Kernel config version (e.g., android15-6.6)'
    required: false
  android_version:
    description: 'Android version (e.g., android15)'
    required: false
  kernel_version:
    description: 'Kernel version (e.g., 6.6)'
    required: false
  os_patch_level:
    description: 'OS patch level (e.g., 2024-07)'
    required: false
  sublevel:
    description: 'Kernel sublevel'
    required: false

runs:
  using: composite
  steps:
    - name: Integrate NoMount in kernel
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        curl https://raw.githubusercontent.com/maxsteeel/nomount/refs/heads/dev/kernel/setup.sh | bash -s dev

    - name: Enable Config
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        echo "CONFIG_NOMOUNT=y" >> ${{ github.workspace }}/wild_gki.fragment
